files: .
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      always_run: true
  - repo: local
    hooks:
      - id: test
        name: run tests
        entry: pytest
        language: python
        types: [python]
        stages: [push]
        always_run: true
          
